Componente calendar.kt (logica de seleccion de hora y fecha)
DevMobUnlam/Alaya pull request #13
Opened 2024-10-03 02:00 UTC by Pacha1810

Implementacion del calendario en la aplicacion.
Contiene la logica para abrir calendario y reloj para seleccion de hora y fecha
![calendar](https://github.com/user-attachments/assets/575a7b49-f9a3-4327-a061-16c9f10ea87a)

2024-10-03 21:41 UTC, FlorSantamaria commented
Lo levante en el celu y en los picker de inicio y fin se corta la fecha, también habría que ver si se puede abrir el calendario y la hora al tocar todo el box y no solo en los iconos, para que sea mas intuitivo

**Evidencia**
![image](https://github.com/user-attachments/assets/21be5edc-b673-4a56-9361-f9a7e8816554)

2024-10-04 00:40 UTC, MuiaLeandro commented on app/src/main/java/com/devmob/alaya/components/calendar.kt
Todas las clases vienen llamándose igual que la función Composable que tienen dentro. En este caso creo que debería ser DateTimePicker.kt

2024-10-04 00:40 UTC, MuiaLeandro commented on app/src/main/java/com/devmob/alaya/components/calendar.kt
Por otro lado, coincido con el comentario de Flor, se ven cortadas las fechas.
Y los colores del modal que se abre para seleccionar la hora o fecha tienen un color que no corresponde (en mi caso los veo verde)
![image](https://github.com/user-attachments/assets/3c6ac25e-97dd-4935-ab6c-7a0ae2468c9b)

2024-10-05 00:51 UTC, BrenMiRo requested changes
cuando seleccionas una fecha se setea ese fecha en el campo de inicio y de fin. Lo mismo pasa con la hora. Por que será? 🤔

2024-10-05 19:38 UTC, Pacha1810 commented
1) Arreglo vista cortada
2) Fecha y hora inicio independientes de fecha y hora final
3) Solo admite fechas actuales y anteriores, no futuras

Falta!!!
1) Cambiar paleta color

![Captura de pantalla de 2024-10-05 16-36-59](https://github.com/user-attachments/assets/b627e10a-6c97-43be-abde-82f332c20cff)

2024-10-05 19:41 UTC, FlorSantamaria submitted a review, later dismissed

2024-10-06 16:41 UTC, soleecito commented on app/src/main/java/com/devmob/alaya/components/DateTimePicker.kt
> +package com.devmob.alaya.components
pasar el componente a la nueva arquitectura -> package com.devmob.alaya.ui.components

2024-10-06 22:01 UTC, BrenMiRo submitted a review, later dismissed

2024-10-07 19:45 UTC, MuiaLeandro submitted a review, later dismissed

2024-10-07 19:45 UTC, MuiaLeandro commented on .idea/other.xml
Me parece que esto va a gitignore porque tiene data de tu dispositivo

2024-10-07 19:45 UTC, MuiaLeandro commented on app/src/main/java/com/devmob/alaya/MainActivity.kt
Cuando mergees main, fijate de sacar tu composable del set content

2024-10-07 20:04 UTC, FlorSantamaria submitted a review, later dismissed

2024-10-08 02:36 UTC, FlorSantamaria approved these changes, later dismissed

2024-10-08 10:31 UTC, CatramboneMauro approved these changes

2024-10-09 00:00 UTC, MuiaLeandro approved these changes

2024-10-09 00:02 UTC, merged