Desarrollo de componente Card
DevMobUnlam/Alaya pull request #7
Opened 2024-09-29 21:57 UTC by FlorSantamaria

**Desarrollo de 3 tipos de Card**

**Card principal**

![image](https://github.com/user-attachments/assets/bb0bd12c-15bc-4f59-809d-a70b20e2c02b)

![image](https://github.com/user-attachments/assets/61fb17cd-c526-45a2-afad-edce9dd57f1c)

**Card de red de contención**

![image](https://github.com/user-attachments/assets/983db87a-ff64-4676-a208-a8998359514e)
![image](https://github.com/user-attachments/assets/c94c9f4f-6dc5-47e1-a75a-8bce62c05358)

**Card actividades diarias**
![image](https://github.com/user-attachments/assets/366bd0ca-22a8-43f8-9419-b1cda18c6f85)
Ejemplo de cuando el progress se completó
![image](https://github.com/user-attachments/assets/a03fc119-179b-49fb-9185-a33b46963a7e)
![image](https://github.com/user-attachments/assets/ed06c060-e2e7-45d0-b528-939d35c7ae57)

2024-09-29 22:17 UTC, FacuSosa approved these changes, later dismissed

2024-09-29 22:51 UTC, MuiaLeandro requested changes

2024-09-29 22:51 UTC, MuiaLeandro commented on .idea/deploymentTargetSelector.xml
Me parece que esto deberia estar en gitignore porque tiene un path de tu pc

2024-09-29 22:51 UTC, MuiaLeandro commented on gradle/libs.versions.toml
Esto no es lo que cambió Sole a la versión 8.2? Corresponde volverlo a 8.5?

2024-09-29 23:46 UTC, FacuSosa commented on gradle/libs.versions.toml
Tenes razón Lean lo acabo de ver y si Sole lo cambio a 8.2 por un tema de compatibilidad

2024-09-30 23:52 UTC, FacuSosa approved these changes

2024-10-01 00:02 UTC, MuiaLeandro approved these changes

2024-10-01 00:06 UTC, merged